"""empty message

Revision ID: 04ef6892366b
Revises: 516ea129b950
Create Date: 2016-08-14 14:25:24.727612

"""

# revision identifiers, used by Alembic.
revision = '04ef6892366b'
down_revision = '516ea129b950'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContrastFilesOrDirectory', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('ContrastFilesOrDirectory', sa.Column('enabled', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'ContrastFilesOrDirectory', 'devices', ['device_id'], ['id'])
    op.drop_column('ContrastFilesOrDirectory', 'version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContrastFilesOrDirectory', sa.Column('version', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'ContrastFilesOrDirectory', type_='foreignkey')
    op.drop_column('ContrastFilesOrDirectory', 'enabled')
    op.drop_column('ContrastFilesOrDirectory', 'device_id')
    ### end Alembic commands ###
