"""empty message

Revision ID: 19d0a72b32f6
Revises: 85dc92369a70
Create Date: 2016-08-09 16:40:23.598044

"""

# revision identifiers, used by Alembic.
revision = '19d0a72b32f6'
down_revision = '85dc92369a70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histroyCommands', sa.Column('command', sa.String(length=512), nullable=True))
    op.drop_column('histroyCommands', 'commands')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histroyCommands', sa.Column('commands', mysql.VARCHAR(length=512), nullable=True))
    op.drop_column('histroyCommands', 'command')
    ### end Alembic commands ###
