"""empty message

Revision ID: 19e1246a1eec
Revises: c6f0677de892
Create Date: 2016-08-11 10:40:33.532438

"""

# revision identifiers, used by Alembic.
revision = '19e1246a1eec'
down_revision = 'c6f0677de892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('business', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'business')
    ### end Alembic commands ###
