"""empty message

Revision ID: 1d8bb067432a
Revises: 4d5a495efc84
Create Date: 2016-08-05 19:11:16.940997

"""

# revision identifiers, used by Alembic.
revision = '1d8bb067432a'
down_revision = '4d5a495efc84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviceGroups', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('deviceGroups', 'groupname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviceGroups', sa.Column('groupname', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('deviceGroups', 'name')
    ### end Alembic commands ###
