"""empty message

Revision ID: 1f73ecc4ca5b
Revises: None
Create Date: 2016-08-19 10:06:22.092738

"""

# revision identifiers, used by Alembic.
revision = '1f73ecc4ca5b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContrastTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastFilesOrDirectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=512), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['ContrastTasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoftwareDistribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('taskGroup', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['taskGroup'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ContrastTaskRelationshipContrastFilesOrDirectory',
    sa.Column('ContrastTask_id', sa.Integer(), nullable=True),
    sa.Column('ContrastFilesOrDirectory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ContrastFilesOrDirectory'], ['ContrastFilesOrDirectory.id'], ),
    sa.ForeignKeyConstraint(['ContrastTask_id'], ['ContrastTasks.id'], )
    )
    op.create_table('SoftwareRelationshipDevice',
    sa.Column('SoftwareDistribution_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SoftwareDistribution_id'], ['SoftwareDistribution.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    op.drop_table('deviceGroups')
    op.add_column(u'deviceTasks', sa.Column('extra_vars', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'deviceTasks', 'extra_vars')
    op.create_table('deviceGroups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('business', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('SoftwareRelationshipDevice')
    op.drop_table('ContrastTaskRelationshipContrastFilesOrDirectory')
    op.drop_table('SoftwareDistribution')
    op.drop_table('ContrastResults')
    op.drop_table('ContrastFilesOrDirectory')
    op.drop_table('ContrastTasks')
    ### end Alembic commands ###
