"""empty message

Revision ID: 21a11578599f
Revises: None
Create Date: 2016-08-14 04:51:37.971742

"""

# revision identifiers, used by Alembic.
revision = '21a11578599f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SoftwareDistribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SoftwareRelationshipDevice',
    sa.Column('SoftwareDistribution_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SoftwareDistribution_id'], ['SoftwareDistribution.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SoftwareRelationshipDevice')
    op.drop_table('SoftwareDistribution')
    ### end Alembic commands ###
