"""empty message

Revision ID: 222adb1e7382
Revises: None
Create Date: 2016-08-19 22:59:24.596128

"""

# revision identifiers, used by Alembic.
revision = '222adb1e7382'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ComplianceRecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviceGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('business', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ApplicationOfRelease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('taskGroup', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['taskGroup'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('deviceGroup', sa.Integer(), nullable=True),
    sa.Column('taskGroup', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deviceGroup'], ['deviceGroup.id'], ),
    sa.ForeignKeyConstraint(['taskGroup'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastFilesOrDirectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=512), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['ContrastTasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoftwareDistribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('taskGroup', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['taskGroup'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('System',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('an', sa.String(length=64), nullable=True),
    sa.Column('sn', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('power_ip', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('post', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ApplicationOfReleaseRelationshipDevice',
    sa.Column('ApplicationOfRelease_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ApplicationOfRelease_id'], ['ApplicationOfRelease.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    op.create_table('ContrastTaskRelationshipContrastFilesOrDirectory',
    sa.Column('ContrastTask_id', sa.Integer(), nullable=True),
    sa.Column('ContrastFilesOrDirectory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ContrastFilesOrDirectory'], ['ContrastFilesOrDirectory.id'], ),
    sa.ForeignKeyConstraint(['ContrastTask_id'], ['ContrastTasks.id'], )
    )
    op.create_table('SoftwareRelationshipDevice',
    sa.Column('SoftwareDistribution_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SoftwareDistribution_id'], ['SoftwareDistribution.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    op.drop_table('deviceGroups')
    op.drop_table('DeploySystem')
    op.drop_constraint(u'devicerelationshipdevicegroup_ibfk_1', 'DeviceRelationshipDeviceGroup', type_='foreignkey')
    op.create_foreign_key(None, 'DeviceRelationshipDeviceGroup', 'deviceGroup', ['deviceGroup_id'], ['id'])
    op.add_column(u'deviceTasks', sa.Column('extra_vars', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'deviceTasks', 'extra_vars')
    op.drop_constraint(None, 'DeviceRelationshipDeviceGroup', type_='foreignkey')
    op.create_foreign_key(u'devicerelationshipdevicegroup_ibfk_1', 'DeviceRelationshipDeviceGroup', 'deviceGroups', ['deviceGroup_id'], ['id'])
    op.create_table('DeploySystem',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tasks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_deploy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('deviceGroups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('business', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('SoftwareRelationshipDevice')
    op.drop_table('ContrastTaskRelationshipContrastFilesOrDirectory')
    op.drop_table('ApplicationOfReleaseRelationshipDevice')
    op.drop_table('System')
    op.drop_table('SoftwareDistribution')
    op.drop_table('ContrastResults')
    op.drop_table('ContrastFilesOrDirectory')
    op.drop_table('Compliance')
    op.drop_table('ApplicationOfRelease')
    op.drop_table('deviceGroup')
    op.drop_table('ContrastTasks')
    op.drop_table('ComplianceRecord')
    ### end Alembic commands ###
