"""empty message

Revision ID: 22e95de86cfb
Revises: 88b7ad136413
Create Date: 2016-08-12 16:45:32.471799

"""

# revision identifiers, used by Alembic.
revision = '22e95de86cfb'
down_revision = '88b7ad136413'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('System',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('an', sa.String(length=64), nullable=True),
    sa.Column('sn', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('power_ip', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.Integer(), nullable=True),
    sa.Column('post', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('SystemDeploy')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SystemDeploy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('an', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sn', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('hostname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('power_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('os_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('taskGroup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['power_id'], [u'devicePowers.id'], name=u'SystemDeploy_ibfk_1'),
    sa.ForeignKeyConstraint(['taskGroup'], [u'deviceTaskGroup.id'], name=u'SystemDeploy_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('System')
    ### end Alembic commands ###
