"""empty message

Revision ID: 26c898767758
Revises: 6ac9a6a484e2
Create Date: 2016-08-14 10:48:16.830812

"""

# revision identifiers, used by Alembic.
revision = '26c898767758'
down_revision = '6ac9a6a484e2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContrastFilesOrDirectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastTaskRelationshipContrastFilesOrDirectory',
    sa.Column('ContrastTask_id', sa.Integer(), nullable=True),
    sa.Column('ContrastFilesOrDirectory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ContrastFilesOrDirectory'], ['ContrastFilesOrDirectory.id'], ),
    sa.ForeignKeyConstraint(['ContrastTask_id'], ['ContrastTasks.id'], )
    )
    op.drop_table('ContrastTaskRelationshipContrastFiles')
    op.drop_table('ContrastFiles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContrastFiles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('path', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('version', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ContrastTaskRelationshipContrastFiles',
    sa.Column('ContrastTask_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ContrastFile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ContrastFile_id'], [u'ContrastFiles.id'], name=u'ContrastTaskRelationshipContrastFiles_ibfk_1'),
    sa.ForeignKeyConstraint(['ContrastTask_id'], [u'ContrastTasks.id'], name=u'ContrastTaskRelationshipContrastFiles_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ContrastTaskRelationshipContrastFilesOrDirectory')
    op.drop_table('ContrastFilesOrDirectory')
    ### end Alembic commands ###
