"""empty message

Revision ID: 4a4bb8372cce
Revises: None
Create Date: 2016-08-13 18:56:47.892544

"""

# revision identifiers, used by Alembic.
revision = '4a4bb8372cce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Compliance', sa.Column('enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Compliance', 'enabled')
    ### end Alembic commands ###
