"""empty message

Revision ID: 4d5a495efc84
Revises: 09607fdb09c9
Create Date: 2016-08-05 18:17:38.219080

"""

# revision identifiers, used by Alembic.
revision = '4d5a495efc84'
down_revision = '09607fdb09c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ip', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ip')
    ### end Alembic commands ###
