"""empty message

Revision ID: 516ea129b950
Revises: 26c898767758
Create Date: 2016-08-14 10:50:51.226261

"""

# revision identifiers, used by Alembic.
revision = '516ea129b950'
down_revision = '26c898767758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContrastFilesOrDirectory', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContrastFilesOrDirectory', 'type')
    ### end Alembic commands ###
