"""empty message

Revision ID: 5d2665390fc2
Revises: d5e9aca66723
Create Date: 2016-08-11 17:09:03.876341

"""

# revision identifiers, used by Alembic.
revision = '5d2665390fc2'
down_revision = 'd5e9aca66723'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskClass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskClass')
    ### end Alembic commands ###
