"""empty message

Revision ID: 607daee486a3
Revises: 04ef6892366b
Create Date: 2016-08-14 16:31:49.626334

"""

# revision identifiers, used by Alembic.
revision = '607daee486a3'
down_revision = '04ef6892366b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContrastTasks', sa.Column('enabled', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContrastTasks', 'enabled')
    ### end Alembic commands ###
