"""empty message

Revision ID: 65548242bb8d
Revises: 750bf7506bf8
Create Date: 2016-08-14 07:01:48.517297

"""

# revision identifiers, used by Alembic.
revision = '65548242bb8d'
down_revision = '750bf7506bf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviceTasks', sa.Column('extra_vars', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deviceTasks', 'extra_vars')
    ### end Alembic commands ###
