"""empty message

Revision ID: 6ac9a6a484e2
Revises: e621537ca35c
Create Date: 2016-08-14 10:25:50.785822

"""

# revision identifiers, used by Alembic.
revision = '6ac9a6a484e2'
down_revision = 'e621537ca35c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContrastFiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastResults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=512), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['ContrastTasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ContrastTaskRelationshipContrastFiles',
    sa.Column('ContrastTask_id', sa.Integer(), nullable=True),
    sa.Column('ContrastFile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ContrastFile_id'], ['ContrastFiles.id'], ),
    sa.ForeignKeyConstraint(['ContrastTask_id'], ['ContrastTasks.id'], )
    )
    op.add_column(u'SoftwareDistribution', sa.Column('instaff', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'SoftwareDistribution', 'instaff')
    op.drop_table('ContrastTaskRelationshipContrastFiles')
    op.drop_table('ContrastResults')
    op.drop_table('ContrastTasks')
    op.drop_table('ContrastFiles')
    ### end Alembic commands ###
