"""empty message

Revision ID: 750bf7506bf8
Revises: 21a11578599f
Create Date: 2016-08-14 05:54:52.445087

"""

# revision identifiers, used by Alembic.
revision = '750bf7506bf8'
down_revision = '21a11578599f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SoftwareDistribution', sa.Column('inputtime', sa.DateTime(), nullable=True))
    op.add_column('SoftwareDistribution', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('SoftwareDistribution', sa.Column('taskGroup', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SoftwareDistribution', 'deviceTaskGroup', ['taskGroup'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SoftwareDistribution', type_='foreignkey')
    op.drop_column('SoftwareDistribution', 'taskGroup')
    op.drop_column('SoftwareDistribution', 'remarks')
    op.drop_column('SoftwareDistribution', 'inputtime')
    ### end Alembic commands ###
