"""empty message

Revision ID: 77a82201a8cf
Revises: None
Create Date: 2016-08-22 13:38:24.727824

"""

# revision identifiers, used by Alembic.
revision = '77a82201a8cf'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DeploySystem')
    op.drop_table('deviceGroups')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviceGroups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('business', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('DeploySystem',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tasks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_deploy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
