"""empty message

Revision ID: 85dc92369a70
Revises: c49ca3edb511
Create Date: 2016-08-09 11:22:01.968417

"""

# revision identifiers, used by Alembic.
revision = '85dc92369a70'
down_revision = 'c49ca3edb511'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histroyCommands', sa.Column('inputtime', sa.DateTime(), nullable=True))
    op.add_column('pushCommandLogger', sa.Column('inputtime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pushCommandLogger', 'inputtime')
    op.drop_column('histroyCommands', 'inputtime')
    ### end Alembic commands ###
