"""empty message

Revision ID: 88b7ad136413
Revises: None
Create Date: 2016-08-12 13:13:21.515546

"""

# revision identifiers, used by Alembic.
revision = '88b7ad136413'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviceGroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('business', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviceTaskGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviceTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskname', sa.String(length=64), nullable=True),
    sa.Column('scriptname', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('arch', sa.Integer(), nullable=True),
    sa.Column('md5code', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moduleClass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('separator', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DeviceRelationshipDeviceGroup',
    sa.Column('deviceGroup_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deviceGroup_id'], ['deviceGroups.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], )
    )
    op.create_table('TaskRelationshipTaskGroup',
    sa.Column('deviceTaskGroup_id', sa.Integer(), nullable=True),
    sa.Column('deviceTask_id', sa.Integer(), nullable=True),
    sa.Column('PQ', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deviceTaskGroup_id'], ['deviceTaskGroup.id'], ),
    sa.ForeignKeyConstraint(['deviceTask_id'], ['deviceTasks.id'], )
    )
    op.create_table('pushCommandLogger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskClass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('separator', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['moduleClass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SystemDeploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('an', sa.String(length=64), nullable=True),
    sa.Column('sn', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('power_id', sa.Integer(), nullable=True),
    sa.Column('os_version', sa.Integer(), nullable=True),
    sa.Column('taskGroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['power_id'], ['devicePowers.id'], ),
    sa.ForeignKeyConstraint(['taskGroup'], ['deviceTaskGroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histroyCommands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Tasks')
    op.drop_table('taskGroup')
    op.drop_table('DeploySystem')
    op.add_column(u'devices', sa.Column('an', sa.String(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('brand', sa.String(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column(u'devices', sa.Column('ip', sa.String(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('manufacturer', sa.String(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('model', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_devices_an'), 'devices', ['an'], unique=True)
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.drop_column(u'devices', 'managestaff')
    op.drop_column(u'devices', 'managedept')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'devices', sa.Column('managedept', mysql.VARCHAR(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('managestaff', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_an'), table_name='devices')
    op.drop_column(u'devices', 'model')
    op.drop_column(u'devices', 'manufacturer')
    op.drop_column(u'devices', 'ip')
    op.drop_column(u'devices', 'device_id')
    op.drop_column(u'devices', 'brand')
    op.drop_column(u'devices', 'an')
    op.create_table('DeploySystem',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tasks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_deploy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('taskGroup',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('Tasks',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('script', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('taskgroup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('md5code', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['taskgroup_id'], [u'taskGroup.id'], name=u'Tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('histroyCommands')
    op.drop_table('SystemDeploy')
    op.drop_table('taskClass')
    op.drop_table('pushCommandLogger')
    op.drop_table('TaskRelationshipTaskGroup')
    op.drop_table('DeviceRelationshipDeviceGroup')
    op.drop_table('moduleClass')
    op.drop_table('deviceTasks')
    op.drop_table('deviceTaskGroup')
    op.drop_table('deviceGroups')
    ### end Alembic commands ###
