"""empty message

Revision ID: 9e2cbd0c31f4
Revises: 4a4bb8372cce
Create Date: 2016-08-13 20:22:06.766208

"""

# revision identifiers, used by Alembic.
revision = '9e2cbd0c31f4'
down_revision = '4a4bb8372cce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('System', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('System', 'type')
    ### end Alembic commands ###
