"""empty message

Revision ID: c49ca3edb511
Revises: 1d8bb067432a
Create Date: 2016-08-09 10:08:56.588841

"""

# revision identifiers, used by Alembic.
revision = 'c49ca3edb511'
down_revision = '1d8bb067432a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushCommandLogger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histroyCommands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commands', sa.String(length=512), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'devices', 'managestaff')
    op.drop_column(u'devices', 'managedept')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'devices', sa.Column('managedept', mysql.VARCHAR(length=64), nullable=True))
    op.add_column(u'devices', sa.Column('managestaff', mysql.VARCHAR(length=64), nullable=True))
    op.drop_table('histroyCommands')
    op.drop_table('pushCommandLogger')
    ### end Alembic commands ###
