"""empty message

Revision ID: c6f0677de892
Revises: 19d0a72b32f6
Create Date: 2016-08-11 10:40:20.064102

"""

# revision identifiers, used by Alembic.
revision = 'c6f0677de892'
down_revision = '19d0a72b32f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'business')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('business', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
