"""empty message

Revision ID: d5e9aca66723
Revises: 19e1246a1eec
Create Date: 2016-08-11 10:46:38.344524

"""

# revision identifiers, used by Alembic.
revision = 'd5e9aca66723'
down_revision = '19e1246a1eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('brand', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('manufacturer', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'manufacturer')
    op.drop_column('devices', 'brand')
    ### end Alembic commands ###
