"""empty message

Revision ID: e621537ca35c
Revises: 1c55086f1e5b
Create Date: 2016-08-14 07:49:07.846105

"""

# revision identifiers, used by Alembic.
revision = 'e621537ca35c'
down_revision = '1c55086f1e5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SoftwareDistribution', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SoftwareDistribution', 'type')
    ### end Alembic commands ###
