"""empty message

Revision ID: e9b9ca19e85b
Revises: 22e95de86cfb
Create Date: 2016-08-12 23:18:20.522928

"""

# revision identifiers, used by Alembic.
revision = 'e9b9ca19e85b'
down_revision = '22e95de86cfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('System', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('System', 'status')
    ### end Alembic commands ###
