"""empty message

Revision ID: efff5d6eb271
Revises: 607daee486a3
Create Date: 2016-08-14 17:04:54.731187

"""

# revision identifiers, used by Alembic.
revision = 'efff5d6eb271'
down_revision = '607daee486a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContrastTasks', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContrastTasks', 'status')
    ### end Alembic commands ###
